### ISSUE TITLE
Use pip to install python packages into site-packages?

### ISSUE THREAD

**Issue by fire** [maiself/godot-python-extension#19]
Extracted from this discussion. https://github.com/maiself/godot-python-extension/issues/9#issuecomment-2264370479

**Comment by Ivorforce** [comment]
I wonder what the best way to support this would be.

I understand the comment from the discussion to include a python and pip runnable, which would make it easy to add packages locally. 

However, this would be incompatible with every other platform, increasing the barrier to export. For some cases, this may be OK, but for others, a deal breaker. Better would be to define the required packages in a file like `requirements.txt`, or better from a full-fledged package manager like [poetry](https://python-poetry.org), [rye](https://rye.astral.sh) or [hatch](https://hatch.pypa.io/latest/), which are officially adopted for publish options.

## Export Options

We have a number of options to deal with exports, and none are really optimal. These are the ones I can think of:

### App Export
One option would then be to automatically install the requirements on launch of the project. This is [analogous to the Hatch workflow of this task](https://hatch.pypa.io/latest/plugins/builder/binary/). However, this requires an internet connection, and likely won't work for web setups.

### Transpile Python

Another option would be to transpile the python scripts using [Nuitka](https://nuitka.net), [Cython](https://cython.org), or [py2wasm](https://github.com/wasmerio/py2wasm). This has the benefit of possibly creating very fast binaries, but can be very error-prone.

### Offload install to GitHub Runner

One could use the requirements file defined above to let GitHub runners install the required packages automatically, providing a downloadable file with pythons that have the required packages installed locally, ready for export.

### Ignore Exports

The final option is the default one, which is just to not officially support exports of projects using python packages for now.

**Comment by fire** [comment]
> Offload install to GitHub Runner 

This would satisfy my requirements for the robust weight transfer that requires https://pypi.org/project/libigl/ and https://pypi.org/project/robust-laplacian/ packages.

It's not general but it would work for me.

**Comment by Ivorforce** [comment]
I managed to install a package via pip!

Currently the process is kinda involved. I'm sure we can make it simpler though.

### Initial steps

It is possible to generate python runnables using the current setup:

```bash
cd <godot-python-extension>
cp ./src/.generated/python/macos-x86_64/python/bin/ ./bin/macos-x86_64/bin/
install_name_tool -change @executable_path/../lib/libpython3.12.dylib @executable_path/../libpython3.12.dylib ./bin/macos-x86_64/bin/python3.12
PYTHONPATH="./bin/macos-x86_64/python312.zip" ./bin/macos-x86_64/bin/python3.12 -m ensurepip
PYTHONPATH="./bin/macos-x86_64/python312.zip" ./bin/macos-x86_64/bin/pip install <packages>
```

This currently installs the packages to ~/.local/. We need to copy it over to bin:

```bash
cp ~/.local/lib/python3.12/site-packages ./bin/macos-x86_64/site-packages
```

This works for normal packages, though it really slows down the launch.

It would be nice to figure out how to tell it to install site-packages into the zip, and remove the ~/.local from the `PYTHONPATH`.

### NumPy

NumPy is currently not possible at all:

```
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

Traceback (most recent call last):
  File "res://bin/macos-x86_64/site-packages/numpy/__init__.py", line 114, in <module>
    from numpy.__config__ import show as show_config
ModuleNotFoundError: No module named 'numpy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "godot/_python_extension/python_script.py", line 350, in _reload
    module = importlib.import_module(module_name) # XXX
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "res://bin/macos-x86_64/site-packages/numpy/__init__.py", line 119, in <module>
    raise ImportError(msg) from e
```
